import { Event } from '../monopoly/pool'

export const chanceList: Event[] = [
  {
    type: 'pay',
    description: '銀行へ15万円支払う。',
    target: 'bank',
    amount: 15,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'repair',
    description:
      '建物の修理費として自分の持っているお店1件あたり25万円、ホテル1件あたり100万円支払う。',
    target: 'bank',
    amount: 0,
    shopCost: 25,
    hotelCost: 100,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'pay',
    description: '各プレイヤーに50万円ずつ支払う。',
    target: 'everyone',
    amount: 50,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'move',
    description: '南鉄道に進む。もしGOを通れば200万円受け取る。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'south_station',
    leverage: 1,
  },
  {
    type: 'move',
    description: '次の鉄道まで進む。もしGOを通れば200万円受け取る。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'station',
    leverage: 2,
  },
  {
    type: 'move',
    description: 'ゲームセンターへ進む。もしGOを通れば、200万円受け取る。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'game_center',
    leverage: 1,
  },
  {
    type: 'move',
    description: '渓流釣りへ進む。もしGOを通れば、200万円受け取る。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'fishing',
    leverage: 1,
  },
  {
    type: 'move',
    description: '次の鉄道まで進む。もしGOを通れば200万円受け取る。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'station',
    leverage: 2,
  },
  {
    type: 'move',
    description: '3マス戻りその指示に従う。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'three',
    leverage: 1,
  },
  {
    type: 'move',
    description: '富士山へ進む。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'fujiyama',
    leverage: 1,
  },
  {
    type: 'move',
    description: '次の水道会社に進む。もしGOを通れば200万円受け取る。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'water',
    leverage: 1,
  },
  {
    type: 'move',
    description: 'GOのマスへ進み、200万円受け取る。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'receive',
    description: '骨董品の壺が高値で売れた。150万円受け取る。',
    target: 'bank',
    amount: 150,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'receive',
    description: '銀行より50万円受け取る。',
    target: 'bank',
    amount: 50,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'go_to_jail',
    description: '刑務所へ行く。もしGOを通っても200万円は受け取れない。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
]

export const challengeList: Event[] = [
  {
    type: 'receive',
    description: '礼金として25万円受け取る。',
    target: 'bank',
    amount: 25,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'move',
    description: 'GOのマスへ進み、200万円受け取る。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'receive',
    description: 'アイデアコンテストで優勝！10万円受け取る。',
    target: 'bank',
    amount: 10,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'move',
    description: 'GOのマスへ進み、200万円受け取る。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'repair',
    description:
      '建物の修理費として自分の持っているお店1件あたり40万円、ホテル1件あたり115万円支払う。',
    target: 'bank',
    amount: 0,
    shopCost: 40,
    hotelCost: 115,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'pay',
    description: '株が暴落。150万円支払う。',
    target: 'bank',
    amount: 150,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'pay',
    description: '銀行へ100万円支払う。',
    target: 'bank',
    amount: 100,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'receive',
    description: '絵画コンクールで金賞！45万円受け取る。',
    target: 'bank',
    amount: 45,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'receive',
    description: '各プレイヤーから50万円ずつ受け取る。',
    target: 'everyone',
    amount: 50,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'receive',
    description: '税金が20万円戻る。',
    target: 'bank',
    amount: 20,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'receive',
    description: '宝くじに当たって100万円受け取る。',
    target: 'bank',
    amount: 100,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'receive',
    description: '銀行より200万円受け取る。',
    target: 'bank',
    amount: 200,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'receive',
    description: '福引で大当たり！世界一周旅行費用として100万円受け取る。',
    target: 'bank',
    amount: 100,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'receive',
    description: '株式売却により100万円受け取る。',
    target: 'bank',
    amount: 100,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
  {
    type: 'go_to_jail',
    description: '刑務所へ行く。もしGOを通っても200万円は受け取れない。',
    target: 'bank',
    amount: 0,
    shopCost: 0,
    hotelCost: 0,
    destination: 'start',
    leverage: 1,
  },
]
