import { Panel } from './pool'

const setPosition = (panelList: Panel[]) => {
  return panelList.map((panel, idx) => {
    return {
      ...panel,
      position: idx,
    }
  })
}

export const initialPanelList: Panel[] = setPosition([
  {
    type: 'action',
    position: 0,
    name: 'Go',
    actionType: 'start',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'scuba',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'action',
    position: 0,
    name: 'チャレンジ',
    actionType: 'challenge',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'ski',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'action',
    position: 0,
    name: '税金',
    actionType: 'tax',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'south_station',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'takoyaki',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'action',
    position: 0,
    name: 'チャンス',
    actionType: 'chance',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'crape',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'ramen',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'action',
    position: 0,
    name: '刑務所',
    actionType: 'jail',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'fishing',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'electricity',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'camp',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'beach',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'west_station',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'skate_stadium',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'action',
    position: 0,
    name: 'チャレンジ',
    actionType: 'challenge',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'soccer_stadium',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'baseball_stadium',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'action',
    position: 0,
    name: '無料駐車場',
    actionType: 'free_parking',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'bowling',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'action',
    position: 0,
    name: 'チャンス',
    actionType: 'chance',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'theater',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'game_center',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'north_station',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'gallery',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'library',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'water',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'museum',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'action',
    position: 0,
    name: '刑務所へ行く',
    actionType: 'go_to_jail',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'zoo',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'aquarium',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'action',
    position: 0,
    name: 'チャレンジ',
    actionType: 'challenge',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'amusement_park',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'east_station',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'action',
    position: 0,
    name: 'チャンス',
    actionType: 'chance',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'tokyo_tower',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
  {
    type: 'action',
    position: 0,
    name: '物品税',
    actionType: 'commodity_tax',
  },
  {
    type: 'asset',
    position: 0,
    assetId: 'fujiyama',
    playerId: null,
    shopCount: 0,
    hotelCount: 0,
    isMortgaged: false,
  },
])
