name: Run Unit Tests

on: [pull_request]

jobs:
  check:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          yarn install
      - name: Check Lint
        run: |
          yarn lint
      - name: Run tests
        run: |
          yarn test
      - name: Check webpack build
        run: |
          yarn test:build:client
          yarn test:build:server
